In [8]:
import pickle
import sys

In [9]:
sys.path.append('../../')

In [11]:
gmm1 = pickle.load(open('../../data/leyanbug/NumeralAsNumeral/gmm/gmm-10-fp-hard.dat', 'rb'))
gmm2 = pickle.load(open('../../data/leyanbug/NumeralAsNumeral/gmm/gmm-10-fp.dat', 'rb'))

In [17]:
gmm1.means_.reshape(-1)

array([  9.51228022,  37.18      ,  56.6125    ,  75.83521445,
        88.65483871, 103.76555024, 126.69072165, 160.64184397,
       174.80412371, 237.66666667])

In [16]:
gmm2.means_.reshape(-1)

array([  9.60484174,  37.00956288,  54.85258887,  76.1776308 ,
        88.37725065, 102.66898127, 124.53973246, 160.95914638,
       172.75880553, 223.68281912])

In [15]:
gmm1.covariances_.reshape(-1)

array([  59.54752133,    9.157601  ,   31.46234475,   15.76065711,
         13.1905421 ,   24.05508216,   81.63630666,   23.12349831,
         16.77606647, 1433.17460417])

In [18]:
gmm2.covariances_.reshape(-1)

array([  61.56772961,    8.19333454,   49.72818597,   23.99885892,
         24.33522564,   43.27523651,  143.55071977,   27.79029302,
         37.80724749, 2237.60228943])